# Slabbo Config

chestlinks: # Linking chests
  enabled: true
  enforcepermission: false # If users need a permission to link a chest
  hoppers: # Hopper functionality for linked chest
    enabled: true
    savetime: 5 # Delay in seconds
  player: # If the player is able to deposit to the chest
    enabled: true
    savetime: 5

itemdisplay: quantity # Quantity (The amount the shop sells) / Full (A full stack (64 items))

checkupdates: true

backupfiles: # If slabbo should create extra files with the shops in
  enabled: true # If it's enabled
  savetime: 300 # How often the files should be created in seconds