name: ${project.name}
version: ${project.version}
main: xyz.mackan.Slabbo.Slabbo
description: ${project.description}
author: Mackan
api-version: 1.16
depend: [Vault]
softdepend: [ClearLag, WorldGuard]
permissions:
  slabbo.use:
    default: op
    description: Lets you use slab shops
  slabbo.create:
    default: op
    description: Lets you create slab shops
  slabbo.admin:
    default: op
    description: Lets you create admin shops
  slabbo.limit.*:
    default: op
    description: Gives you unlimited shops
  slabbo.destroy:
    default: op
    description: Lets you destroy your shops
  slabbo.destroy.others:
    default: op
    description: Lets you destroy other peoples shops

  slabbo.modify.self.buyprice:
    default: op
    description: Lets you modify the buy price of shops with a command
  slabbo.modify.self.sellprice:
    default: op
    description: Lets you modify the sell price of shops with a command
  slabbo.modify.self.quantity:
    default: op
    description: Lets you modify the quantity of shops with a command

  slabbo.modify.self.*:
    default: op
    description: Gives you access to all the modification commands
    children:
      slabbo.modify.self.buyprice: true
      slabbo.modify.self.sellprice: true
      slabbo.modify.self.quantity: true

  slabbo.modify.others.buyprice:
    default: op
    description: Lets you modify the buy price of other peoples shops
  slabbo.modify.others.sellprice:
    default: op
    description: Lets you modify the sell price of other peoples shops
  slabbo.modify.others.quantity:
    default: op
    description: Lets you modify the quantity of other peoples shops.

  slabbo.modify.others.*:
    default: op
    description: Gives you access to use all the modification commands for other peoples shops
    children:
      slabbo.modify.others.buyprice: true
      slabbo.modify.others.sellprice: true
      slabbo.modify.others.quantity: true

  slabbo.link:
    default: op
    description: Lets you link a shop to a chest

  slabbo.notifyupdate:
    default: op
    description: Shows you the update notification when you join