name: ${project.name}
version: ${project.version}
main: xyz.mackan.Slabbo.Slabbo
description: ${project.description}
author: Mackan
api-version: 1.16
depend: [Vault]
permissions:
  slabbo.use:
    default: op
    description: Lets you use slab shops
  slabbo.create:
    default: op
    description: Lets you create slab shops
  slabbo.admin:
    default: op
    description: Lets you create admin shops
  slabbo.limit.*:
    default: op
    description: Gives you unlimited shops
  slabbo.destroy:
    default: op
    description: Lets you destroy your shops
  slabbo.destroy.others:
    default: op
    description: Lets you destroy other peoples shops

  slabbo.modify:
    default: op
    description: Lets you use /slabbo modify

  slabbo.modify.buyprice.others:
    default: op
    description: Lets you modify the buy price of other peoples shops
  slabbo.modify.sellprice.others:
    default: op
    description: Lets you modify the sell price of other peoples shops
  slabbo.modify.quantity.others:
    default: op
    description: Lets you modify the quantity of other peoples shops.

  slabbo.modify.buyprice:
    default: op
    description: Lets you modify the buy price of shops with a command
  slabbo.modify.sellprice:
    default: op
    description: Lets you modify the sell price of shops with a command
  slabbo.modify.quantity:
    default: op
    description: Lets you modify the quantity of shops with a command

  slabbo.modify.*:
    default: op
    description: Gives you access to all the modification commands
    children:
      slabbo.modify.buyprice: true
      slabbo.modify.sellprice: true
      slabbo.modify.quantity: true

  slabbo.modify.*.others:
    default: op
    description: Gives you access to use all the modification commands for other peoples shops
    children:
      slabbo.modify.buyprice.others: true
      slabbo.modify.sellprice.others: true
      slabbo.modify.quantity.others: true
